### ISSUE TITLE
Start Turntable Scan...

### ISSUE THREAD

**Issue by nodswal** [hdonk/eora3D#2]
I just found this project and I am very excited to start getting the eora3d to scan and create any kind of model.  I have posted it on reddit for a subreddit r/3dscanning.

Thus far my process is the launch the batch file in Windows.
       I do not calibrate as seems to require each circle in the corner to be centered and spent about 20 minutes trying to complete this. Until I can figure out a better method(maybe attaching the camera to a camera stabilizer so small changes aren't so large).
I hit detect, it finds the Laser and Turntable.
even though the USB camera is listed as the camera I still expand it and select "Logitech HD Pro Webcam C910"
I hit "Scan" to go into the section to start scanning.
        *The picture is rotated 90 degrees, so the left side is on the top
I do "Laser start position" and "Laser end position" and narrow them down to 3200 and 5500.
       At this point the laser is left on with no way to turn it off.  I don't do this any more since I have it narrowed down.

I can do "Start scan" and the laser will sweep, **BUT** I when I do "Start turntable scan" the laser never comes on, though the turntable will do its rotation.  The the error message "Timed out waiting for the laser motor start" and it will incrementally rotate and spit out that error in the command prompt.

Other thoughts
maybe a 3D print can be used to thin out the laser, a slot in the print?  Maybe I will try to test that in the future.

**Comment by hdonk** [comment]
Thanks for the issue. I'll have a look (shortly :/ ) and get back to you.
I also want to create a video showing how to do manual calibration, for your case.

**Comment by nodswal** [comment]
I tried looking for a Facebook group but did not see one. I read your wiki (after the fact, sorry.  I have dyslexia so wordy text is difficult for me), I think it set me straight on manual calibration, it looks like you can line the laser up with the outside dots on the left and right of the calibration board?  I don't think that would be the issue for the laser not coming on during the rotation process, just how accurate the 3d model will be?  If the Linux app is better I will try that. Any kind of guides you do would be great.  Getting my orientation in the program was probably the hardest part, so a video on getting started would be much appreciated and helpful.  Keep up the great work, and stay safe.

**Comment by bolsoncerrado** [comment]
https://www.facebook.com/groups/1466378826778053/ for the fb "experience"

**Comment by hdonk** [comment]
I've reproduced the issue, am now debugging.

**Comment by hdonk** [comment]
Fixed in Windows 10 0.0.4 release. Was an issue with the Eora3D using the same 'UUID' for motor position indications from the Laser & the Turntable.
