### ISSUE TITLE
Errors running bat for Windows10

### ISSUE THREAD

**Issue by hoopty1** [hdonk/eora3D#3]
Hey Nick 

I think we spoke before a while back before you had released any code. Anyway I am getting some errors about BLE and GATT. I have Windows 10 Pro and java 1.8(latest release 251) and a dell desktop with Bluetooth. I do have the IP from my phone entered in the "IP Camera URL" http://192.168.1.120:8080/photo.jpg

I read the instructions a few times and it did not say I had to install anything, but I am thinking I might be missing something.

I have the IP WebCam installed on my android phone, connected to the local subnet started the server for sharing, and still ("I got a rock" like Charlie Brown says) You may not have Charlie Brown in the UK so I apologize if you missed that reference. 
![nick4](https://user-images.githubusercontent.com/64755609/80927993-8de98880-8d6f-11ea-800c-7d0e6b574993.PNG)

I click the DETECT button and here is what I see:
![nick1](https://user-images.githubusercontent.com/64755609/80927966-5da1ea00-8d6f-11ea-969b-ba6c6d4dce1d.PNG)
![nick2](https://user-images.githubusercontent.com/64755609/80927970-62669e00-8d6f-11ea-8bdc-5ad993c379aa.PNG)
![nick3](https://user-images.githubusercontent.com/64755609/80927974-67c3e880-8d6f-11ea-8998-6ede0ba7c752.PNG)
I press the camera button and I get Camera is null. and the

**Comment by hdonk** [comment]
Hi. Thanks for the issue. Is this with the latest 0.0.4 build?

**Comment by hoopty1** [comment]
Yes sir. Does it look like a bug or am I doing something wrong?

**Comment by hdonk** [comment]
Looks like either something wrong in my bluetooth code, or Eora had two versions of firmware on the laser/turntable.
I'll put together a debug version.

**Comment by hdonk** [comment]
Please can you download "Bluetooth LE Explorer" from the Microsoft store, and then attach a screen cap of the "Device Services Page" for both the E3DT and E3DS devices?
Here's an example of what I'd like to see:
![Annotation 2020-05-05 092059](https://user-images.githubusercontent.com/2048452/81047286-05273580-8eb2-11ea-96ac-f181093112ef.png)

**Comment by hoopty1** [comment]
Sorry I have been away the last few days.
![image](https://user-images.githubusercontent.com/64755609/81484722-02ac3f00-9216-11ea-8331-0cd271ef3e5d.png)
![image](https://user-images.githubusercontent.com/64755609/81484733-1061c480-9216-11ea-8b48-6ec5ccd0a352.png)

**Comment by hoopty1** [comment]
Let me know what else I can do.

**Comment by hdonk** [comment]
Those uuids look fine. I'll have to do a debug build after all... How far is your Eora from your PC?

**Comment by hdonk** [comment]
Also, which build of Windows 10 are you on? I'm on 1909...

**Comment by hoopty1** [comment]
I am 1909. I was right next to my PC when I did the screenshots

**Comment by hoopty1** [comment]
Now I feel bad. I think you can close this issue. It seems it is just a bit wonky now and then.
