### ISSUE TITLE
Original calibration sheet as PDF

### ISSUE THREAD

**Issue by SchmollTroll** [hdonk/eora3D#4]
Hi there,

saw the request for the calibration sheet  in the EORA 3D User Group and remebered that I've downloaded it when it still was available from Eora.

So I hope this is useful for anybody...

[Eora3D-CalibrationBoard.pdf](https://github.com/hdonk/eora3D/files/4626960/Eora3D-CalibrationBoard.pdf)

**Comment by hdonk** [comment]
Excellent, thanks. I've added it to the repo.

**Comment by ShreddinPB** [comment]
definitely needed that, thanks!
