### ISSUE TITLE
Trying to get it to run on Mac 

### ISSUE THREAD

**Issue by CastroSATT** [hdonk/eora3D#7]
So first issue could not find java had to change normal run script to

```
#!/bin/sh
JAVA_BIN=/Library/Java/JavaVirtualMachines/jdk-13.0.2.jdk/Contents/Home/bin/java
RUN_ROOT=.
cd eora3D
```

now I get 

Air:scripts jma$ sh run_eora3D.sh
run_eora3D.sh: line 4: cd: eora3D: No such file or directory
Error: Could not find or load main class eora3D.eora3D
Caused by: java.lang.ClassNotFoundException: eora3D.eora3D
Air:scripts jma$ 

btw I'am so new to java and any language except really python, if that. Be gentle haha 

I have purchased the scanner super cheap and I would love to you use it or at least get point clouds from it.....im normally a hardware guy... the tech specs should be decent the software thus far is dead......youve done a great job so far from what I can see in this early stage.i just can't understand why companies won't just open source when they go bust or defunct... funny enough a lot of them preach to go green but let there products become  paperweights

**Comment by hdonk** [comment]
Unfortunately it won't work on MacOS even if you get the java to run - you'll need someone to implement a BLE/Java support library. Best bet would be to use a Windows 10 VM or in a pinch Linux - The Linux version is behind the Windows 10 version.

**Comment by CastroSATT** [comment]
Yeah will give it a go on Linux in few days see what the fuss is about thanks again will keep you updated also have you found the FCC id would be interesting to see the insides 

JMA

**Comment by CastroSATT** [comment]
Cool so I have the unit now got it up and running on windows 10 with parallels finding and initialising Both unit seems to go ok sometimes but sometime just crashes the OS, when it does connect I get this error trying to initiate scan this is after some very rudimentary calibration  

https://drive.google.com/drive/folders/1VrTRB-dTuXL_wox9Ofpy5sCDTEco0tOS

What I don’t get is that the turret when connects first time does a quick look around so not sure what the error means in context 





Also What distro do you recommend for getting it going on Linux haven’t had much success yet (will try again ina few day ) wondering if it would clear the error
